In [10]:
import pandas as pd

In [11]:
df = pd.read_csv("/Users/nipun/Desktop/pm25-2017.csv")

In [12]:
df

,local,location,city,country,value,unit,latitude,longitude
0,2017-01-01 00:00:00,Income Tax Office,Delhi,IN,512.00,µg/m³,28.62350,77.24940
1,2017-01-01 00:15:00,Siri Fort,Delhi,IN,195.00,µg/m³,NaN,NaN
2,2017-01-01 00:15:00,Income Tax Office,Delhi,IN,511.00,µg/m³,28.62350,77.24940
3,2017-01-01 00:20:00,Punjabi Bagh,Delhi,IN,178.00,µg/m³,28.66830,77.11670
4,2017-01-01 00:25:00,Anand Vihar,Delhi,IN,132.00,µg/m³,28.65080,77.31520
5,2017-01-01 00:25:00,Mandir Marg,Delhi,IN,164.00,µg/m³,28.63410,77.20050
6,2017-01-01 00:30:00,Income Tax Office,Delhi,IN,515.00,µg/m³,28.62350,77.24940
7,2017-01-01 00:30:00,US Diplomatic Post: New Delhi,Delhi,IN,188.80,µg/m³,28.63576,77.22445
8,2017-01-01 00:45:00,Siri Fort,Delhi,IN,195.60,µg/m³,NaN,NaN
9,2017-01-01 00:45:00,Income Tax Office,Delhi,IN,515.00,µg/m³,28.62350,77.24940
10,2017-01-01 00:50:00,Punjabi Bagh,Delhi,IN,174.00,µg/m³,28.66830,77.11670
11,2017-01-01 00:55:00,Anand Vihar,Delhi,IN,210.00,µg/m³,28.65080,77.31520
12,2017-01-01 00:55:00,Mandir Marg,Delhi,IN,164.00,µg/m³,28.63410,77.20050
13,2017-01-01 01:00:00,Income Tax Office,Delhi,IN,513.00,µg/m³,28.62350,77.24940
14,2017-01-01 01:15:00,Siri Fort,Delhi,IN,208.20,µg/m³,NaN,NaN
15,2017-01-01 01:15:00,Income Tax Office,Delhi,IN,502.00,µg/m³,28.62350,77.24940
16,2017-01-01 01:20:00,Punjabi Bagh,Delhi,IN,174.00,µg/m³,28.66830,77.11670
17,2017-01-01 01:25:00,Anand Vihar,Delhi,IN,210.00,µg/m³,28.65080,77.31520
18,2017-01-01 01:25:00,Mandir Marg,Delhi,IN,164.00,µg/m³,28.63410,77.20050
19,2017-01-01 01:30:00,Income Tax Office,Delhi,IN,484.00,µg/m³,28.62350,77.24940
20,2017-01-01 01:30:00,US Diplomatic Post: New Delhi,Delhi,IN,188.50,µg/m³,28.63576,77.22445
21,2017-01-01 01:45:00,Siri Fort,Delhi,IN,207.50,µg/m³,NaN,NaN
22,2017-01-01 01:45:00,Income Tax Office,Delhi,IN,470.00,µg/m³,28.62350,77.24940
23,2017-01-01 01:50:00,Punjabi Bagh,Delhi,IN,152.00,µg/m³,28.66830,77.11670
24,2017-01-01 01:55:00,Anand Vihar,Delhi,IN,192.00,µg/m³,28.65080,77.31520
25,2017-01-01 01:55:00,Mandir Marg,Delhi,IN,150.00,µg/m³,28.63410,77.20050
26,2017-01-01 02:00:00,Income Tax Office,Delhi,IN,460.00,µg/m³,28.62350,77.24940
27,2017-01-01 02:15:00,Siri Fort,Delhi,IN,193.90,µg/m³,NaN,NaN
28,2017-01-01 02:15:00,Income Tax Office,Delhi,IN,459.00,µg/m³,28.62350,77.24940
29,2017-01-01 02:20:00,Punjabi Bagh,Delhi,IN,152.00,µg/m³,28.66830,77.11670
...,...,...,...,...,...,...,...,...
187834,2017-12-31 22:15:00,"NSIT Dwarka, Delhi - CPCB",Delhi,IN,387.00,µg/m³,28.59100,77.05000
187835,2017-12-31 22:15:00,"Delhi Technological University, Delhi - CPCB",Delhi,IN,213.00,µg/m³,28.74400,77.12000
187836,2017-12-31 22:30:00,US Diplomatic Post: New Delhi,Delhi,IN,377.00,µg/m³,28.63576,77.22445
187837,2017-12-31 22:30:00,"IHBAS, Delhi - CPCB",Delhi,IN,204.20,µg/m³,28.68210,77.30500
187838,2017-12-31 22:30:00,"Shadipur, Delhi - CPCB",Delhi,IN,460.70,µg/m³,28.65170,77.15810
187839,2017-12-31 22:30:00,"Sirifort, Delhi - CPCB",Delhi,IN,422.00,µg/m³,NaN,NaN
187840,2017-12-31 22:45:00,"IHBAS, Delhi - CPCB",Delhi,IN,147.70,µg/m³,28.68210,77.30500
187841,2017-12-31 22:45:00,"Sirifort, Delhi - CPCB",Delhi,IN,387.00,µg/m³,NaN,NaN
187842,2017-12-31 22:45:00,"Shadipur, Delhi - CPCB",Delhi,IN,474.50,µg/m³,28.65170,77.15810
187843,2017-12-31 22:45:00,"NSIT Dwarka, Delhi - CPCB",Delhi,IN,317.90,µg/m³,28.59100,77.05000
187844,2017-12-31 23:00:00,"Income Tax Office, Delhi - CPCB",Delhi,IN,168.00,µg/m³,28.62350,77.24940
187845,2017-12-31 23:00:00,"Aya Nagar, Delhi - IMD",Delhi,IN,408.65,µg/m³,NaN,NaN
187846,2017-12-31 23:00:00,"IGI Airport Terminal-3, Delhi - IMD",Delhi,IN,316.22,µg/m³,NaN,NaN
187847,2017-12-31 23:00:00,"North Campus, Delhi - IMD",Delhi,IN,262.92,µg/m³,NaN,NaN
187848,2017-12-31 23:00:00,"Pusa, Delhi - IMD",Delhi,IN,259.72,µg/m³,NaN,NaN
187849,2017-12-31 23:00:00,"Burari Crossing, Delhi - IMD",Delhi,IN,187.40,µg/m³,NaN,NaN
187850,2017-12-31 23:00:00,"CRRI Mathura Road, Delhi - IMD",Delhi,IN,439.82,µg/m³,NaN,NaN
187851,2017-12-31 23:00:00,"Shadipur, Delhi - CPCB",Delhi,IN,517.00,µg/m³,28.65170,77.15810
187852,2017-12-31 23:00:00,"IHBAS, Delhi - CPCB",Delhi,IN,145.00,µg/m³,28.68210,77.30500
187853,2017-12-31 23:00:00,"NSIT Dwarka, Delhi - CPCB",Delhi,IN,317.90,µg/m³,28.59100,77.05000
187854,2017-12-31 23:00:00,"Delhi Technological University, Delhi - CPCB",Delhi,IN,202.00,µg/m³,28.74400,77.12000
187855,2017-12-31 23:15:00,"Delhi Technological University, Delhi - CPCB",Delhi,IN,202.00,µg/m³,28.74400,77.12000
187856,2017-12-31 23:30:00,"Shadipur, Delhi - CPCB",Delhi,IN,517.00,µg/m³,28.65170,77.15810
187857,2017-12-31 23:30:00,"IHBAS, Delhi - CPCB",Delhi,IN,145.00,µg/m³,28.68210,77.30500
187858,2017-12-31 23:30:00,"Delhi Technological University, Delhi - CPCB",Delhi,IN,202.00,µg/m³,28.74400,77.12000
187859,2017-12-31 23:30:00,"Sirifort, Delhi - CPCB",Delhi,IN,386.00,µg/m³,NaN,NaN
187860,2017-12-31 23:30:00,US Diplomatic Post: New Delhi,Delhi,IN,405.00,µg/m³,28.63576,77.22445
187861,2017-12-31 23:45:00,"IHBAS, Delhi - CPCB",Delhi,IN,131.10,µg/m³,28.68210,77.30500
187862,2017-12-31 23:45:00,"Sirifort, Delhi - CPCB",Delhi,IN,389.00,µg/m³,NaN,NaN
187863,2017-12-31 23:45:00,"NSIT Dwarka, Delhi - CPCB",Delhi,IN,263.70,µg/m³,28.59100,77.05000

In [13]:
df.index = pd.to_datetime(df.local)

In [14]:
df

,local,location,city,country,value,unit,latitude,longitude
local,,,,,,,,
2017-01-01 00:00:00,2017-01-01 00:00:00,Income Tax Office,Delhi,IN,512.00,µg/m³,28.62350,77.24940
2017-01-01 00:15:00,2017-01-01 00:15:00,Siri Fort,Delhi,IN,195.00,µg/m³,NaN,NaN
2017-01-01 00:15:00,2017-01-01 00:15:00,Income Tax Office,Delhi,IN,511.00,µg/m³,28.62350,77.24940
2017-01-01 00:20:00,2017-01-01 00:20:00,Punjabi Bagh,Delhi,IN,178.00,µg/m³,28.66830,77.11670
2017-01-01 00:25:00,2017-01-01 00:25:00,Anand Vihar,Delhi,IN,132.00,µg/m³,28.65080,77.31520
2017-01-01 00:25:00,2017-01-01 00:25:00,Mandir Marg,Delhi,IN,164.00,µg/m³,28.63410,77.20050
2017-01-01 00:30:00,2017-01-01 00:30:00,Income Tax Office,Delhi,IN,515.00,µg/m³,28.62350,77.24940
2017-01-01 00:30:00,2017-01-01 00:30:00,US Diplomatic Post: New Delhi,Delhi,IN,188.80,µg/m³,28.63576,77.22445
2017-01-01 00:45:00,2017-01-01 00:45:00,Siri Fort,Delhi,IN,195.60,µg/m³,NaN,NaN
2017-01-01 00:45:00,2017-01-01 00:45:00,Income Tax Office,Delhi,IN,515.00,µg/m³,28.62350,77.24940
2017-01-01 00:50:00,2017-01-01 00:50:00,Punjabi Bagh,Delhi,IN,174.00,µg/m³,28.66830,77.11670
2017-01-01 00:55:00,2017-01-01 00:55:00,Anand Vihar,Delhi,IN,210.00,µg/m³,28.65080,77.31520
2017-01-01 00:55:00,2017-01-01 00:55:00,Mandir Marg,Delhi,IN,164.00,µg/m³,28.63410,77.20050
2017-01-01 01:00:00,2017-01-01 01:00:00,Income Tax Office,Delhi,IN,513.00,µg/m³,28.62350,77.24940
2017-01-01 01:15:00,2017-01-01 01:15:00,Siri Fort,Delhi,IN,208.20,µg/m³,NaN,NaN
2017-01-01 01:15:00,2017-01-01 01:15:00,Income Tax Office,Delhi,IN,502.00,µg/m³,28.62350,77.24940
2017-01-01 01:20:00,2017-01-01 01:20:00,Punjabi Bagh,Delhi,IN,174.00,µg/m³,28.66830,77.11670
2017-01-01 01:25:00,2017-01-01 01:25:00,Anand Vihar,Delhi,IN,210.00,µg/m³,28.65080,77.31520
2017-01-01 01:25:00,2017-01-01 01:25:00,Mandir Marg,Delhi,IN,164.00,µg/m³,28.63410,77.20050
2017-01-01 01:30:00,2017-01-01 01:30:00,Income Tax Office,Delhi,IN,484.00,µg/m³,28.62350,77.24940
2017-01-01 01:30:00,2017-01-01 01:30:00,US Diplomatic Post: New Delhi,Delhi,IN,188.50,µg/m³,28.63576,77.22445
2017-01-01 01:45:00,2017-01-01 01:45:00,Siri Fort,Delhi,IN,207.50,µg/m³,NaN,NaN
2017-01-01 01:45:00,2017-01-01 01:45:00,Income Tax Office,Delhi,IN,470.00,µg/m³,28.62350,77.24940
2017-01-01 01:50:00,2017-01-01 01:50:00,Punjabi Bagh,Delhi,IN,152.00,µg/m³,28.66830,77.11670
2017-01-01 01:55:00,2017-01-01 01:55:00,Anand Vihar,Delhi,IN,192.00,µg/m³,28.65080,77.31520
2017-01-01 01:55:00,2017-01-01 01:55:00,Mandir Marg,Delhi,IN,150.00,µg/m³,28.63410,77.20050
2017-01-01 02:00:00,2017-01-01 02:00:00,Income Tax Office,Delhi,IN,460.00,µg/m³,28.62350,77.24940
2017-01-01 02:15:00,2017-01-01 02:15:00,Siri Fort,Delhi,IN,193.90,µg/m³,NaN,NaN
2017-01-01 02:15:00,2017-01-01 02:15:00,Income Tax Office,Delhi,IN,459.00,µg/m³,28.62350,77.24940
2017-01-01 02:20:00,2017-01-01 02:20:00,Punjabi Bagh,Delhi,IN,152.00,µg/m³,28.66830,77.11670
...,...,...,...,...,...,...,...,...
2017-12-31 22:15:00,2017-12-31 22:15:00,"NSIT Dwarka, Delhi - CPCB",Delhi,IN,387.00,µg/m³,28.59100,77.05000
2017-12-31 22:15:00,2017-12-31 22:15:00,"Delhi Technological University, Delhi - CPCB",Delhi,IN,213.00,µg/m³,28.74400,77.12000
2017-12-31 22:30:00,2017-12-31 22:30:00,US Diplomatic Post: New Delhi,Delhi,IN,377.00,µg/m³,28.63576,77.22445
2017-12-31 22:30:00,2017-12-31 22:30:00,"IHBAS, Delhi - CPCB",Delhi,IN,204.20,µg/m³,28.68210,77.30500
2017-12-31 22:30:00,2017-12-31 22:30:00,"Shadipur, Delhi - CPCB",Delhi,IN,460.70,µg/m³,28.65170,77.15810
2017-12-31 22:30:00,2017-12-31 22:30:00,"Sirifort, Delhi - CPCB",Delhi,IN,422.00,µg/m³,NaN,NaN
2017-12-31 22:45:00,2017-12-31 22:45:00,"IHBAS, Delhi - CPCB",Delhi,IN,147.70,µg/m³,28.68210,77.30500
2017-12-31 22:45:00,2017-12-31 22:45:00,"Sirifort, Delhi - CPCB",Delhi,IN,387.00,µg/m³,NaN,NaN
2017-12-31 22:45:00,2017-12-31 22:45:00,"Shadipur, Delhi - CPCB",Delhi,IN,474.50,µg/m³,28.65170,77.15810
2017-12-31 22:45:00,2017-12-31 22:45:00,"NSIT Dwarka, Delhi - CPCB",Delhi,IN,317.90,µg/m³,28.59100,77.05000
2017-12-31 23:00:00,2017-12-31 23:00:00,"Income Tax Office, Delhi - CPCB",Delhi,IN,168.00,µg/m³,28.62350,77.24940
2017-12-31 23:00:00,2017-12-31 23:00:00,"Aya Nagar, Delhi - IMD",Delhi,IN,408.65,µg/m³,NaN,NaN
2017-12-31 23:00:00,2017-12-31 23:00:00,"IGI Airport Terminal-3, Delhi - IMD",Delhi,IN,316.22,µg/m³,NaN,NaN
2017-12-31 23:00:00,2017-12-31 23:00:00,"North Campus, Delhi - IMD",Delhi,IN,262.92,µg/m³,NaN,NaN
2017-12-31 23:00:00,2017-12-31 23:00:00,"Pusa, Delhi - IMD",Delhi,IN,259.72,µg/m³,NaN,NaN
2017-12-31 23:00:00,2017-12-31 23:00:00,"Burari Crossing, Delhi - IMD",Delhi,IN,187.40,µg/m³,NaN,NaN
2017-12-31 23:00:00,2017-12-31 23:00:00,"CRRI Mathura Road, Delhi - IMD",Delhi,IN,439.82,µg/m³,NaN,NaN
2017-12-31 23:00:00,2017-12-31 23:00:00,"Shadipur, Delhi - CPCB",Delhi,IN,517.00,µg/m³,28.65170,77.15810
2017-12-31 23:00:00,2017-12-31 23:00:00,"IHBAS, Delhi - CPCB",Delhi,IN,145.00,µg/m³,28.68210,77.30500
2017-12-31 23:00:00,2017-12-31 23:00:00,"NSIT Dwarka, Delhi - CPCB",Delhi,IN,317.90,µg/m³,28.59100,77.05000
2017-12-31 23:00:00,2017-12-31 23:00:00,"Delhi Technological University, Delhi - CPCB",Delhi,IN,202.00,µg/m³,28.74400,77.12000
2017-12-31 23:15:00,2017-12-31 23:15:00,"Delhi Technological University, Delhi - CPCB",Delhi,IN,202.00,µg/m³,28.74400,77.12000
2017-12-31 23:30:00,2017-12-31 23:30:00,"Shadipur, Delhi - CPCB",Delhi,IN,517.00,µg/m³,28.65170,77.15810
2017-12-31 23:30:00,2017-12-31 23:30:00,"IHBAS, Delhi - CPCB",Delhi,IN,145.00,µg/m³,28.68210,77.30500
2017-12-31 23:30:00,2017-12-31 23:30:00,"Delhi Technological University, Delhi - CPCB",Delhi,IN,202.00,µg/m³,28.74400,77.12000
2017-12-31 23:30:00,2017-12-31 23:30:00,"Sirifort, Delhi - CPCB",Delhi,IN,386.00,µg/m³,NaN,NaN
2017-12-31 23:30:00,2017-12-31 23:30:00,US Diplomatic Post: New Delhi,Delhi,IN,405.00,µg/m³,28.63576,77.22445
2017-12-31 23:45:00,2017-12-31 23:45:00,"IHBAS, Delhi - CPCB",Delhi,IN,131.10,µg/m³,28.68210,77.30500
2017-12-31 23:45:00,2017-12-31 23:45:00,"Sirifort, Delhi - CPCB",Delhi,IN,389.00,µg/m³,NaN,NaN
2017-12-31 23:45:00,2017-12-31 23:45:00,"NSIT Dwarka, Delhi - CPCB",Delhi,IN,263.70,µg/m³,28.59100,77.05000

In [5]:
df.location.unique()

array(['Income Tax Office', 'Siri Fort', 'Punjabi Bagh', 'Anand Vihar',
       'Mandir Marg', 'US Diplomatic Post: New Delhi', 'R K Puram',
       'Delhi Technological University', 'IHBAS', 'Shadipur',
       'NSIT Dwarka', 'IGI Airport Terminal-3, Delhi - IMD',
       'Burari Crossing, Delhi - IMD', 'Lodhi Road, Delhi - IMD',
       'North Campus, Delhi - IMD', 'CRRI Mathura Road, Delhi - IMD',
       'Pusa, Delhi - IMD', 'Aya Nagar, Delhi - IMD', 'Pusa2 IMD',
       'Punjabi Bagh, Delhi - DPCC',
       'Delhi Technological University, Delhi - CPCB',
       'Sirifort, Delhi - CPCB', 'Shadipur, Delhi - CPCB',
       'NSIT Dwarka, Delhi - CPCB', 'IHBAS, Delhi - CPCB',
       'Income Tax Office, Delhi - CPCB', 'Anand Vihar, Delhi - DPCC',
       'R K Puram, Delhi - DPCC', 'Mandir Marg, Delhi - DPCC'], dtype=object)

In [8]:
temp = []
for loc in df.location.unique():
    print(loc)
    t = df[df.location==loc].resample("1D").mean()
    t.to_csv(loc.strip() +".csv")

Income Tax Office
Siri Fort
Punjabi Bagh
Anand Vihar
Mandir Marg
US Diplomatic Post: New Delhi
R K Puram
Delhi Technological University
IHBAS
Shadipur
NSIT Dwarka
IGI Airport Terminal-3, Delhi - IMD
Burari Crossing, Delhi - IMD
Lodhi Road, Delhi - IMD
North Campus, Delhi - IMD
CRRI Mathura Road, Delhi - IMD
Pusa, Delhi - IMD
Aya Nagar, Delhi - IMD
Pusa2 IMD
Punjabi Bagh, Delhi - DPCC
Delhi Technological University, Delhi - CPCB
Sirifort, Delhi - CPCB
Shadipur, Delhi - CPCB
NSIT Dwarka, Delhi - CPCB
IHBAS, Delhi - CPCB
Income Tax Office, Delhi - CPCB
Anand Vihar, Delhi - DPCC
R K Puram, Delhi - DPCC
Mandir Marg, Delhi - DPCC

In [9]:
pd.read_csv("R K Puram.csv")

          local       value  latitude  longitude
0    2017-01-03  222.000000   28.5648    77.1744
1    2017-01-04  214.250000   28.5648    77.1744
2    2017-01-05  311.375000   28.5648    77.1744
3    2017-01-06  184.108108   28.5648    77.1744
4    2017-01-07  164.973684   28.5648    77.1744
5    2017-01-08  227.500000   28.5648    77.1744
6    2017-01-09  184.105263   28.5648    77.1744
7    2017-01-10  130.088235   28.5648    77.1744
8    2017-01-11  227.750000   28.5648    77.1744
9    2017-01-12  237.187500   28.5648    77.1744
10   2017-01-13  355.450000   28.5648    77.1744
11   2017-01-14  411.000000   28.5648    77.1744
12   2017-01-15         NaN       NaN        NaN
13   2017-01-16  138.233333   28.5648    77.1744
14   2017-01-17  187.000000   28.5648    77.1744
15   2017-01-18  193.578947   28.5648    77.1744
16   2017-01-19  149.550000   28.5648    77.1744
17   2017-01-20  182.692308   28.5648    77.1744
18   2017-01-21         NaN       NaN        NaN
19   2017-01-22         NaN       NaN        NaN
20   2017-01-23         NaN       NaN        NaN
21   2017-01-24  173.833333   28.5648    77.1744
22   2017-01-25  192.968750   28.5648    77.1744
23   2017-01-26  124.707317   28.5648    77.1744
24   2017-01-27  187.000000   28.5648    77.1744
25   2017-01-28  107.500000   28.5648    77.1744
26   2017-01-29         NaN       NaN        NaN
27   2017-01-30   63.600000   28.5648    77.1744
28   2017-01-31  135.727273   28.5648    77.1744
29   2017-02-01  244.640000   28.5648    77.1744
..          ...         ...       ...        ...
300  2017-10-30  205.000000   28.5648    77.1744
301  2017-10-31  296.437500   28.5648    77.1744
302  2017-11-01  178.347826   28.5648    77.1744
303  2017-11-02  210.044444   28.5648    77.1744
304  2017-11-03  205.216667   28.5648    77.1744
305  2017-11-04  239.725806   28.5648    77.1744
306  2017-11-05  210.228070   28.5648    77.1744
307  2017-11-06  279.733333   28.5648    77.1744
308  2017-11-07  512.800000   28.5648    77.1744
309  2017-11-08  711.000000   28.5648    77.1744
310  2017-11-09  472.630435   28.5648    77.1744
311  2017-11-10  330.956522   28.5648    77.1744
312  2017-11-11  417.521739   28.5648    77.1744
313  2017-11-12  445.323944   28.5648    77.1744
314  2017-11-13  343.542373   28.5648    77.1744
315  2017-11-14  285.934426   28.5648    77.1744
316  2017-11-15  180.125000   28.5648    77.1744
317  2017-11-16  209.619048   28.5648    77.1744
318  2017-11-17  153.363636   28.5648    77.1744
319  2017-11-18         NaN       NaN        NaN
320  2017-11-19  169.000000   28.5648    77.1744
321  2017-11-20  167.363636   28.5648    77.1744
322  2017-11-21  237.000000   28.5648    77.1744
323  2017-11-22  176.043478   28.5648    77.1744
324  2017-11-23  181.857143   28.5648    77.1744
325  2017-11-24  196.750000   28.5648    77.1744
326  2017-11-25  246.800000   28.5648    77.1744
327  2017-11-26  299.000000   28.5648    77.1744
328  2017-11-27  239.764706   28.5648    77.1744
329  2017-11-28  183.555556   28.5648    77.1744

[330 rows x 4 columns]

In [17]:
temp = []
for loc in df.location.unique():
    print(loc)
    t = df[df.location==loc].resample("1D").mean()
    t['location'] = loc
    temp.append(t)
pd.concat(temp).to_csv("PM25-daily-2017.csv")

Income Tax Office
Siri Fort
Punjabi Bagh
Anand Vihar
Mandir Marg
US Diplomatic Post: New Delhi
R K Puram
Delhi Technological University
IHBAS
Shadipur
NSIT Dwarka
IGI Airport Terminal-3, Delhi - IMD
Burari Crossing, Delhi - IMD
Lodhi Road, Delhi - IMD
North Campus, Delhi - IMD
CRRI Mathura Road, Delhi - IMD
Pusa, Delhi - IMD
Aya Nagar, Delhi - IMD
Pusa2 IMD
Punjabi Bagh, Delhi - DPCC
Delhi Technological University, Delhi - CPCB
Sirifort, Delhi - CPCB
Shadipur, Delhi - CPCB
NSIT Dwarka, Delhi - CPCB
IHBAS, Delhi - CPCB
Income Tax Office, Delhi - CPCB
Anand Vihar, Delhi - DPCC
R K Puram, Delhi - DPCC
Mandir Marg, Delhi - DPCC

In [18]:
!head PM25-daily-2017.csv

local,value,latitude,longitude,location
2017-01-01,556.0736842105263,28.62350000000001,77.2493999999999,Income Tax Office
2017-01-02,264.1578947368421,28.62350000000001,77.2493999999999,Income Tax Office
2017-01-03,189.45679012345678,28.623499999999986,77.24939999999994,Income Tax Office
2017-01-04,152.20833333333334,28.62350000000001,77.2493999999999,Income Tax Office
2017-01-05,201.44791666666666,28.62350000000001,77.2493999999999,Income Tax Office
2017-01-06,152.96875,28.62350000000001,77.2493999999999,Income Tax Office
2017-01-07,110.22916666666667,28.62350000000001,77.2493999999999,Income Tax Office
2017-01-08,141.20833333333334,28.62350000000001,77.2493999999999,Income Tax Office
2017-01-09,120.77083333333333,28.62350000000001,77.2493999999999,Income Tax Office